=== FlorianHeigl/docgen/etc/docgen.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- $Id: docgen.dtd 161 2008-09-28 01:20:15Z daedalus $ -->
<!-- DocGen Document Type Definition for <project/> -->

<!ELEMENT project (background, revision+, database*, site+, snapvaultset*, snapmirrorset*, backuppolicy*, backupscheduleset*, backupmedia*)>
  <!ATTLIST project name CDATA #REQUIRED
                    code CDATA #REQUIRED
                    title CDATA #REQUIRED>

  <!-- <background/> element contains verbatim DocBook XML to be
    included in the background section of the document
  -->
  <!ELEMENT background ANY>
    <!-- These are here so that things inside the background tag are passed as valid
         What this should really do is import the DocBook schema and use it for anything
	 inside the background element. No idea how to do that yet.
    -->
    <!ELEMENT para ANY>
    <!ELEMENT itemizedlist ANY>
    <!ELEMENT listitem ANY>

  <!-- Revision History elements -->
  <!ELEMENT revision EMPTY>
  <!ATTLIST revision majornumber CDATA #REQUIRED
                     minornumber CDATA #REQUIRED
                     date CDATA #REQUIRED
                     author CDATA #REQUIRED
                     revremark CDATA #IMPLIED
                     reviewer CDATA #IMPLIED
                     reviewdate CDATA #IMPLIED
                     description CDATA #IMPLIED>

  <!ELEMENT database (onhost*, filesystem*, backup*)>
    <!ATTLIST database id ID #IMPLIED>
    <!ATTLIST database type CDATA #REQUIRED>

    <!ELEMENT onhost EMPTY>
      <!ATTLIST onhost name IDREF #REQUIRED>
    <!ELEMENT backup EMPTY>
      <!ATTLIST backup type (streaming | vnas) #REQUIRED
                       online ( yes | no ) #IMPLIED
		       scheduleset IDREF #REQUIRED>

  <!ELEMENT site (vlan+, host*, filer+)>
    <!ATTLIST site name CDATA #IMPLIED
                   type CDATA #IMPLIED
                   location CDATA #IMPLIED>

    <!ELEMENT filer (name?, vfiler?)>
      <!ATTLIST filer type (filer | nearstore) 'filer'
                      partner CDATA #IMPLIED
                      name ID #REQUIRED>

      <!ELEMENT vfiler (name?, protocol*, ipaddress+, aggregate*, igroup*)>
        <!ATTLIST vfiler name CDATA #IMPLIED>
        <!ELEMENT protocol EMPTY>
          <!ATTLIST protocol name (nfs | cifs | iscsi) #REQUIRED>

        <!ELEMENT ipaddress EMPTY>
	  <!ATTLIST ipaddress type (primary|alias|service|test) 'primary'
                              ip CDATA #REQUIRED
                              netmask CDATA #IMPLIED
                              vlan_number CDATA #IMPLIED>

        <!ELEMENT aliasip (ipaddr, netmask)>

        <!ELEMENT vlanip (ipaddr, netmask?)>
	  <!ATTLIST vlanip vlan CDATA #REQUIRED>

        <!ELEMENT testip (ipaddr, netmask)>

	<!ELEMENT igroup (member+)>
	  <!ATTLIST igroup name ID #REQUIRED>
	  <!ATTLIST igroup number CDATA #IMPLIED>
	  <!ATTLIST igroup prefix CDATA #IMPLIED>
	  <!ATTLIST igroup suffix CDATA #IMPLIED>
	  <!ELEMENT member EMPTY>
	    <!ATTLIST member name IDREF #REQUIRED>

        <!ELEMENT aggregate (autosize?, autodelete?, volume*)>
         <!ATTLIST aggregate name CDATA #REQUIRED
                             type CDATA #IMPLIED>

	<!-- The volume declaration -->
	<!ELEMENT volume (autosize?, autodelete?, (qtree | lun | export | setref | exportalias)* )>
	  <!ATTLIST volume type (oraconfig | oracm | oradata | oraindx | oraredo | oraundo | oraarch ) #IMPLIED
	                   name ID #IMPLIED
                           usable CDATA #IMPLIED
                           description CDATA #IMPLIED
			   prefix CDATA #IMPLIED
			   suffix CDATA #IMPLIED
			   snapreserve CDATA #IMPLIED
			   snapstorage CDATA #IMPLIED
			   proto CDATA #IMPLIED
			   oracle IDREF #IMPLIED
			   restartnumbering CDATA #IMPLIED
			   oplocks (yes|no) 'no'
			   iscsi_snapspace CDATA #IMPLIED
                           space_guarantee CDATA #IMPLIED>

	  <!ELEMENT usablestorage (#PCDATA)>
	  <!ELEMENT snapstorage (#PCDATA)>
          <!ELEMENT autosize EMPTY>
            <!ATTLIST autosize max CDATA #IMPLIED
                               increment CDATA #IMPLIED>
          <!ELEMENT autodelete EMPTY>
            <!ATTLIST autodelete commitment (try | disrupt) #IMPLIED
                                 trigger (volume | snap_reserve | space_reserve) #IMPLIED
                                 target_free_space CDATA #IMPLIED
                                 delete_order (newest_first | oldest_first) #IMPLIED
                                 defer_delete (scheduled | user_created | prefix | none) #IMPLIED
                                 prefix CDATA #IMPLIED>

	  <!ELEMENT qtree (lun*, exportalias*)>
	    <!ATTLIST qtree name CDATA #IMPLIED
                            description CDATA #IMPLIED
	              oplocks (yes|no) 'no'>

          <!ELEMENT lun (export*, mapto*)>
	    <!ATTLIST lun size CDATA #IMPLIED
	                  name CDATA #IMPLIED
			  lunid CDATA #IMPLIED
			  restartnumbering CDATA #IMPLIED>
	    <!ELEMENT mapto EMPTY>
	      <!ATTLIST mapto igroup IDREF #REQUIRED>

          <!ELEMENT export (mountoption*)>
	    <!ATTLIST export to IDREF #IMPLIED
		             fromip CDATA #IMPLIED
		             toip CDATA #IMPLIED
	                     ro (yes|no) 'no'>
            <!ELEMENT mountoption (#PCDATA)>			     

          <!ELEMENT exportalias (#PCDATA)>

	  <!ELEMENT setref EMPTY>
	    <!ATTLIST setref type (snap | snapvault | snapmirror | snapvaultmirror | snapmirrorvault) #REQUIRED
                             name IDREF #REQUIRED>

	  <!ELEMENT protectionref EMPTY>
            <!ATTLIST protectionref name IDREF #REQUIRED>

  <!ELEMENT host (filesystem*, netinterface*, backup*, iscsi_initiator?, drhost*)>
    <!ATTLIST host name ID #REQUIRED
                   platform CDATA #REQUIRED
                   operatingsystem CDATA #REQUIRED
                   location CDATA #REQUIRED
                   description CDATA #IMPLIED
	      virtual (yes | no) 'no'>

    <!ELEMENT filesystem (name*, storage+) >
      <!ATTLIST filesystem type ( local | san | nas | database ) #REQUIRED
                           backup ( yes | no ) #IMPLIED>
      <!ELEMENT storage (#PCDATA)>
        <!ATTLIST storage type (binary | data) #REQUIRED>

    <!ELEMENT netinterface (vlan_number*, switchname?, switchport?, hostport?, ipaddress?)>
      <!ATTLIST netinterface type CDATA #REQUIRED
                mode (active|passive|trunk) 'active'
		mtu CDATA #IMPLIED>
      <!ELEMENT switchname (#PCDATA)>
      <!ELEMENT switchport (#PCDATA)>
      <!ELEMENT hostport (#PCDATA)>
      <!ELEMENT vlan_number (#PCDATA)>

    <!ELEMENT vlan (network*)>
      <!ATTLIST vlan type (project|services) 'project'
	               number CDATA #REQUIRED
		       network CDATA #IMPLIED
		       netmask CDATA #IMPLIED
		       gateway CDATA #IMPLIED
		       mtu CDATA #IMPLIED>
        <!ELEMENT network EMPTY>
	  <!ATTLIST network number CDATA #REQUIRED
		            netmask CDATA #IMPLIED
		            gateway CDATA #REQUIRED>

    <!ELEMENT iscsi_initiator (#PCDATA)>
    <!ELEMENT drhost EMPTY>
      <!ATTLIST drhost name IDREF #REQUIRED>

  <!ELEMENT snapvaultset (snapvaultdef*)>
    <!ATTLIST snapvaultset name ID #REQUIRED
                           targetfiler IDREF #IMPLIED
                           targetvolume CDATA #IMPLIED
			   targetaggregate CDATA #IMPLIED
			   targetusable CDATA #IMPLIED
			   multiplier CDATA #IMPLIED>

    <!ELEMENT snapvaultdef EMPTY>
      <!ATTLIST snapvaultdef basename CDATA #REQUIRED
                             snapschedule CDATA #IMPLIED
                             snapvaultschedule CDATA #IMPLIED>

  <!ELEMENT snapmirrorset (snapmirrordef*)>
    <!ATTLIST snapmirrorset name ID #REQUIRED
                            targetfiler CDATA #IMPLIED
			    targetaggregate CDATA #IMPLIED>
    <!ELEMENT snapmirrordef EMPTY>
      <!ATTLIST snapmirrordef minute CDATA #REQUIRED
                              hour CDATA #REQUIRED
                              dayofmonth CDATA #REQUIRED
                              dayofweek CDATA #REQUIRED>

  <!--
      These elements are used for defining Protection Policies with
      NetApp Protection Manager.
    -->      
  <!ELEMENT protectionpolicy EMPTY>
    <!ATTLIST protectionpolicy name ID #REQUIRED
                               dfmserver CDATA #IMPLIED>

  <!--
      The following elements are used for defining NetBackup backup
      policies in NetBackup 5.1 and above.
    -->

  <!--  backup schedule elements -->
  <!ELEMENT backupscheduleset (backupschedule+)>
    <!ATTLIST backupscheduleset name ID #REQUIRED>

    <!ELEMENT backupschedule (type, frequency, days?, starttime?, endtime?, duration?)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT frequency (#PCDATA)>
    <!ELEMENT days (#PCDATA)>
    <!ELEMENT starttime (#PCDATA)>
    <!ELEMENT endtime (#PCDATA)>
    <!ELEMENT duration (#PCDATA)>

  <!-- change scheduleset to idref -->
  <!ELEMENT backuppolicy (masterserver?, storageunit, advancedclient?)>
    <!ATTLIST backuppolicy name ID #IMPLIED
                           scheduleset IDREF #REQUIRED
                           type (Standard | SQLServer | Oracle | Windows-NT) #IMPLIED>
    <!ELEMENT masterserver (#PCDATA)>
    <!ELEMENT storageunit (#PCDATA)>
    <!ELEMENT advancedclient (snapshot)>
      <!ELEMENT snapshot ( (offhost | alternateclient), (timefinder | vxvm)*)>
        <!ATTLIST snapshot retain (yes | no) #IMPLIED>
        <!ELEMENT offhost (altclient | datamover)>
          <!ELEMENT altclient (#PCDATA)>
          <!ELEMENT datamover EMPTY>
	    <!ATTLIST datamover type (MediaServer) #REQUIRED>

        <!ELEMENT timefinder EMPTY>
          <!ATTLIST timefinder keep (yes | no) #REQUIRED>

        <!ELEMENT vxvm EMPTY>
          <!ATTLIST vxvm backgroundresync (yes | no) #REQUIRED
	                 maxsnapshots CDATA #REQUIRED>
  
  <!ELEMENT backupmedia (amount)>
    <!ELEMENT amount (#PCDATA)>

=== FlorianHeigl/docgen/doc/examples/EXAMPLE.project-definition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is an example project definition file for the DocGen.
Use this file as a reference for how you might configure a project.
It contains examples of how to configure various features of a project,
though not all of them will be present in every project.

-->

<!-- The DOCTYPE for the project contains a computer readable Document Type Definition
that can be used by programs such as 'xmllint' to verify that your defintion
file is well-formed and also a valid file.
-->
<!DOCTYPE project SYSTEM "http://docgen.eigenmagic.com/docgen.dtd">

<!-- All projects contain one, and only one, 'project' tag -->
<project name="eigenmagic" code="001" title="My Project">

  <!-- The background tag contains verbatim DocBook XML markup that is inserted
       into the Background section of the design document. Use this to insert some
       explanatory background text about the project, of required.
  -->
  <background>
    <para>The environment consists of Solaris servers at the primary site.
    </para>

    <itemizedlist>
      <listitem>
	<para>3 x Sun Solaris Servers
	</para>
      </listitem>

    </itemizedlist>

  </background>

  <!-- Design revision history -->
  <!-- Every time you modify the design, you should add a revision, to track
       who makes changes, a summary of what they were, and when they were made.
    -->
  <revision majornumber="1"
            minornumber="0"
            date="31 July 2007"
            author="JPW"
            reviewer="Someone"
            reviewdate="3 August 2008"
            revremark="Initial version"/>

  <revision majornumber="2"
            minornumber="0"
            date="10 July 2009"
            author="JPW"
            reviewer="Someone else"
            reviewdate="9 August 2009"
            revremark="Updated to add some storage."/>

  <!-- Every project host that needs shared storage should be defined here. 
       The 'name' attribute for the tag is a unique name for the host that
       can be used elsewhere in the definition to refer specifically to this host.
  -->


  <!-- Databases can be defined to ease the defininion of exports.
       Define a database by specifying its 'id' and 'type'. The id
       attribute is the database SID (for Oracle) or equivalent unique
       name for other databases.
       
       Each database may exist on one or more hosts, which is defined
       using the <onhost/> tag. It has one attribute: 'name', which
       is the unique hostname that the database exists on. This is used
       to look up the host, defined above.
       
       By using this mechanism, you can define all the volumes for a database,
       and the volumes will be exported rw to all the hosts listed in
       <onhost/> tags for the database. This will also be combined with the
       host's <drhost/> tags to automatically export to the appropriate
       hosts at DR for snapmirrored volumes.
       
       This will likely be used with automated backup designs in the future.
  -->
  <database id="MYDB01" type="Oracle">
    <onhost name="primhost01"/>
    <onhost name="primhost02"/>
  </database>

  <!-- Every project will have a 'primary' site. This is the site that
       the storage is provided from.
       The 'secondary' site is always the SnapMirror destination site.
  -->
  <site name='sitea' type="primary" location="PrimarySite">

    <!-- Every site requires a VLAN for the project, at a minimum.
	 There can only be one 'project' VLAN.
	 It has the following attributes:
	 'type': the type of vlan. 'project' for project VLANs
	 or 'services' for services VLANs, described below.
	 'number': the VLAN number, assigned by networks.
	 'gateway': the IP address for the VRF in the VLAN. This
	 may not be used, but should always be assigned.
    -->
    <vlan type="project" number="3003">
      <network number="10.240.4.0/26" gateway="10.240.4.254"/>
    </vlan>

    <vlan type="services" number="3544">
      <network number="10.10.10.0" netmask="255.255.255.0" gateway="10.459.11.336"/>
    </vlan>

    <vlan type="services" number="3189">
      <network number="10.80.90.0" netmask="255.255.255.0" gateway="10.189.14.8"/>
    </vlan>

    <host name="primhost01"
          platform="Sun"
          operatingsystem="Solaris 10"
          location="Primary Site"
          description="Database server">

      <netinterface type='storage' mode='active'>
	<switchname>sitea-swtedg-0103</switchname>
	<switchport>GigabitEthernet1/1</switchport>
	<hostport>PCI 0</hostport>
	<ipaddress ip="10.240.4.232"/>
      </netinterface>

      <netinterface type='storage' mode='passive'>
	<switchname>sitea-swtedg-0104</switchname>
	<switchport>GigabitEthernet1/1</switchport>
	<hostport>PCI 1</hostport>
      </netinterface>

      <iscsi_initiator>an.iscsi.initname</iscsi_initiator>
      <drhost name='drtesthost01'/>

    </host>

    <!-- Continue to add hosts, one at a time, for every host in the project. -->
    <host name="primhost02"
          platform="Sun"
          operatingsystem="Solaris 10"
          location="Primary Site"
          description="Database server">

      <netinterface type='storage' mode='active'>
	<switchname>sitea-swtedg-0103</switchname>
	<switchport>GigabitEthernet1/2</switchport>
	<hostport>PCI 0</hostport>
	<ipaddress ip="10.240.4.234"/>
      </netinterface>


      <drhost name="drtesthost01"/>
      <drhost name="drtesthost02"/>

    </host>

    <host name="primhost03"
          platform="Sun"
          operatingsystem="Solaris 10"
          location="Primary Site"
          description="Database server">

      <netinterface type='storage' mode='active'>
	<switchname>sitea-swtedg-0103</switchname>
	<switchport>GigabitEthernet1/3</switchport>
	<hostport>PCI 0</hostport>
	<ipaddress ip="10.240.4.235"/>
      </netinterface>

      <drhost name="drtesthost02"/>

    </host>

    <host name="virtualhost-01" virtual="yes"
          platform="Sun"
          operatingsystem="Solaris 10"
          location="Primary Site"
          description="Database server">

      <netinterface type='storage' mode='active'>
	<!--      <switchname>sitea-swtedg-0103</switchname>
	     <switchport>GigabitEthernet1/3</switchport>
	     <hostport>PCI 0</hostport> -->
	<ipaddress ip="10.240.4.238"/>
      </netinterface>

      <drhost name="drtesthost02"/>

    </host>

    <host name="examplehost-01" virtual="yes"
          platform="Sun"
          operatingsystem="Solaris 10"
          location="Primary Site"
          description="Database server">

      <netinterface type='storage' mode='active'>
	<!--      <switchname>sitea-swtedg-0103</switchname>
	     <switchport>GigabitEthernet1/3</switchport>
	     <hostport>PCI 0</hostport> -->
	<ipaddress ip="10.240.4.201"/>
      </netinterface>

    </host>

    <!-- Now we have the filer definitions. There will need to be 3:
	 - The 'primary' filer, which is used for providing the storage.
	 - The 'secondary' filer, which is the cluster partner for the primary.
	 - The 'nearstore' filer, which is used for backups.
	 The 'name' parameter is the unique name of the filer device.
    -->
    <filer type="filer" name="sitea-fashda-01">

      <!-- A vfiler must be defined for the primary.
	   - If no 'name' attribute is specified, it defaults to the same
	   as the project shortname. This will be the case for 99% of
	   designs, and the generator may break if you actually specify a name.
	   - The 'rootaggr' attribute must be supplied. It defines which
	   aggregate on the filer will be used for the vfiler root volume.
      -->
      <vfiler>
	<!-- Each protocol supported by the vfiler should be specified here.
	     Valid values are: NFS, CIFS, and iSCSI
	     
	     This will automatically add any protocols you may have missed, so
	     this tag is optional.
	-->
<!--
	<protocol name="nfs" />
	<protocol name="cifs" />
-->
	<!--
	    Each filer must have a primary ipaddress. This is the IP address used to
	    provide the storage to the hosts.
	-->
        <ipaddress type="primary" ip="10.240.4.225"/>

	<!-- Define service ipaddress if you need a services VLAN.
	     This IP address will be added to the vfiler on an netinterface
	     in the services VLAN so you can access external services, such
	     as ActiveDirectory for doing CIFS authentication.
	-->
	<ipaddress type="service" vlan_number="3544" ip="10.10.10.15"/>

	<!-- volumes exist within aggregates, so for each aggregate you
	     want to use, define an aggregate like this.
	-->
        <aggregate name="aggr01" type="root"/>

	<aggregate name="aggr02">

	  <!-- Inside the aggregate, define volumes in the order you
	       need them. These are just the primary volumes, as any
	       volumes that are created as a result of snapvaults or
	       snapmirrors will be automatically created by the system.
	       
	       Volume names are defined automatically, based on the
	       name of the vfiler and the order of the volumes in this
	       file. A root volume will always be defined for a vfiler
	       using the 'rootaggr' parameter above.
	       
	       Volumes can have a 'type' attribute that will enable
	       additional processing for special volumes. This is
	       mostly used for database volumes where there are
	       standard rules for the snap reserve, qtree names, etc. The
	       default volume type is an NFS data volume with a single qtree
	       named 'data'.
	       
	       The parameter 'snapreserve' is used to define the snapreserve
	       amount required for the volume. This is a float value specifying
	       the percentage snap reserve. It defaults to 20, ie. 20%
	       
	  -->

	  <!-- An Oracle quorum volume. Every project with databases
	       will need one of these. It isn't backed up or mirrored.
	  -->
	  <volume type="oracm" snapreserve="0" usable="1"/>

	  <!--
	      The 'oraconfig' volume is defined second. There is only
